### ISSUE TITLE
US14: As the serverdealer I end the round once the player that raised last is reached again in order that next round can start.

### ISSUE THREAD

**Issue by sanoj765** [sopra-fs21-group-03/Server#10]
- [x] If no one raised, the round is finished once the starting player is reached (again) 
- [x] After round is finished, the next round will start if the previous round was not the last round and more than one player is still in the gameround
- [x] If there is only one player left he wins the gameround

**Comment by mr-carlitos** [comment]
Case now: The Big Blind is considered as a Raiser and therefore if everyone calls in the first round, the Big Blind will not be on turn a second time, even though he should be able to make a decision again. This needs to be fixed

**Comment by mr-carlitos** [comment]
This took me about 6h
