### ISSUE TITLE
If a user folds, he is removed from the turn queue and automatically loses the round

### ISSUE THREAD

**Issue by Samy1101** [sopra-fs21-group-03/Server#42]
Time estimate:  4 hours
This task is part of user story #5

**Comment by mr-carlitos** [comment]
Automatically loses the round -> he shouldn't have the chance to win something in the pot -> The User needs to be removed from the Pot Entity, so that he can't win anything.

**Comment by mr-carlitos** [comment]
https://github.com/sopra-fs21-group-03/Server/commit/485abcb0114e509fad22ad390bf4a096deb2d266

**Comment by mr-carlitos** [comment]
This took me about 4 hours (with writing tests). I guess this took 4h because I had to get used to write Spring-Java-Code again.
