### ISSUE TITLE
US9: As the playing user I want to be able to fold in order to get out of the gameround.

### ISSUE THREAD

**Issue by sanoj765** [sopra-fs21-group-03/Server#5]
- [x] Once user folds, he has lost the round
- [x] Big or small blind cannot fold until they have raised the minimum
- [x] After the fold it’s the next users turn
- [x] If all users except one have folded, the remaining user wins automatically

**Comment by mr-carlitos** [comment]
This took me and Sämi 11.5 h (not each, in total I mean)
