### ISSUE TITLE
US10: As the playing user I want to be able to raise in order to increase the amount of the community pot.

### ISSUE THREAD

**Issue by sanoj765** [sopra-fs21-group-03/Server#6]
- [x] User needs to have at least the amount of money he wants to raise
- [x] The money the user raises gets removed from his own pot and added to the community pot
- [x] After the raise, it’s the next users turn
- [x] Once player has raised he can no longer raise this round
- [x] If a player went all in he is not able to raise anymore

**Comment by mr-carlitos** [comment]
This took me about 7h so far

**Comment by mr-carlitos** [comment]
I tried to implement "All-In" the follwing way: If a Player went All-In (therefore, he has no money left), he should not be able to be on turn again. Therefore, he also is not able to raise again.
